# Generated by Django 2.2.7 on 2019-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
