# Generated by Django 2.2.7 on 2019-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20191201_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
