# Generated by Django 2.2.7 on 2019-12-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20191203_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='last_modified',
        ),
    ]
