# Generated by Django 2.2.7 on 2019-12-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20191203_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
