# Generated by Django 2.2.7 on 2019-12-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_movie_totalseasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Title',
        ),
    ]
