# Generated by Django 2.2.7 on 2019-12-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_remove_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('id', 'Title')},
        ),
    ]
