# Generated by Django 2.2.7 on 2019-12-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20191204_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
