# Generated by Django 2.2.7 on 2019-12-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment_id',
        ),
    ]
