# Generated by Django 2.2.7 on 2019-12-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_auto_20191204_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
