# Generated by Django 2.2.7 on 2019-12-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_auto_20191206_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='last_modified',
            new_name='last_date',
        ),
    ]
