# Generated by Django 2.2.7 on 2019-12-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_auto_20191207_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='start_date',
        ),
    ]
