# Generated by Django 2.2.7 on 2019-12-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_auto_20191207_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genre',
        ),
    ]
