# Generated by Django 2.2.7 on 2019-12-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_auto_20191210_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
