# Generated by Django 2.2.7 on 2019-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_auto_20191213_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
