# Generated by Django 2.2.7 on 2019-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_movie_myvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
