# Generated by Django 2.2.7 on 2019-12-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_auto_20191214_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='start',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='end',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='myVariable',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start_date',
        ),
    ]
