# Generated by Django 2.2.7 on 2019-12-17 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0030_auto_20191217_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 15, 38, 31, 854962, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
