# Generated by Django 2.2.7 on 2019-12-17 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_auto_20191217_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 15, 41, 41, 279999, tzinfo=utc), verbose_name='date'),
        ),
    ]
