# Generated by Django 2.2.7 on 2019-12-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_auto_20191218_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
    ]
